### ISSUE TITLE
ga.nlp.processor.train gives error

### ISSUE THREAD

**Issue by AndreasHenningsson** [graphaware/neo4j-nlp-opennlp#4]
When executing the following commando: 
CALL ga.nlp.processor.train({textProcessor: "com.graphaware.nlp.processor.opennlp.OpenNLPTextProcessor", modelIdentifier: "test", alg: "ner", inputFile: "test.train", trainingParameters: {iter: 10}})

Result: 
Failed to invoke procedure `ga.nlp.processor.train`: Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error while training NER model test

test.train is located in the importfolder and looks like this (only contains one sentence):
Hello <START:person> asakumando <END> how are you today. 

The database i completly empty

**Comment by AndreasHenningsson** [comment]
I can se that github removes the < and the > and the end but is there around the Word asakumando

**Comment by ikwattro** [comment]
@AndreasHenningsson Do you have any other log lines in the neo4j logs ?

**Comment by ikwattro** [comment]
also, can you share with us the training file > nlp@graphaware.com

**Comment by AndreasHenningsson** [comment]
Attaching the train file.


Nothing particular in the logfiles

Using the following jar-files
•	graphaware-nlp-3.3.2.52.6
•	nlp-opennlp-3.3.2.52.6
•	nlp-stanfordnlp-3.3.2.52.6
[test.zip](https://github.com/graphaware/neo4j-nlp-opennlp/files/1807141/test.zip)

@ikwattro

**Comment by ikwattro** [comment]
@AndreasHenningsson 

We realise here that we miss some documentation, and some polishing to be done to return more useful errors.

You best provide the full path to your file, for example : 

CALL ga.nlp.processor.train({textProcessor: "com.graphaware.nlp.processor.opennlp.OpenNLPTextProcessor", modelIdentifier: "test", alg: "ner", inputFile: "/Users/ikwattro/dev/_graphs/tour/import/train.test", trainingParameters: {iter: 10}})

Also, training with only one sentence will throw an InsufficientTrainingDataException from OpenNLP, you can see a minimum size of training data that works here : 

https://raw.githubusercontent.com/graphaware/neo4j-nlp-opennlp/master/src/main/resources/com/graphaware/nlp/processor/opennlp/en-ner-person.test

**Comment by AndreasHenningsson** [comment]
Hi,
I have checked in the log files and there is nothing there.
What I can se in the train() method it seems like there is somthing with
the statement below since the log entry never occur.
try (ObjectStream<String> lineStream = openFile(fileIn);
NameSampleDataStream sampleStream = new NameSampleDataStream(lineStream))

I get the following error in neos debug.log; dont know if it is connected
to this issue


2018-03-13 17:43:31.744+0000 ERROR
[o.n.b.v.t.BoltMessagingProtocolV1Handler] Failed to write response to
driver Network channel towards /127.0.0.1:57608 is closed. Client has
probably been stopped.
org.neo4j.bolt.v1.packstream.PackOutputClosedException: Network channel
towards /127.0.0.1:57608 is closed. Client has probably been stopped.
at org.neo4j.bolt.v1.transport.ChunkedOutput.ensure(ChunkedOutput.java:166)
at
org.neo4j.bolt.v1.transport.ChunkedOutput.writeShort(ChunkedOutput.java:95)
at
org.neo4j.bolt.v1.packstream.PackStream$Packer.packStructHeader(PackStream.java:440)
at
org.neo4j.bolt.v1.messaging.BoltResponseMessageWriter.onSuccess(BoltResponseMessageWriter.java:89)
at
org.neo4j.bolt.v1.messaging.MessageProcessingHandler.onFinish(MessageProcessingHandler.java:100)
at
org.neo4j.bolt.v1.runtime.BoltStateMachine.after(BoltStateMachine.java:109)
at
org.neo4j.bolt.v1.runtime.BoltStateMachine.ackFailure(BoltStateMachine.java:155)
at
org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onAckFailure$1(BoltMessageRouter.java:77)
at
org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:152)
at
org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:104)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:109)



2018-03-13 15:40 GMT+01:00 Christophe Willemsen <notifications@github.com>:

**Comment by AndreasHenningsson** [comment]
It "works" if a CALL ga.nlp.processor.train(....... in the sence that i dont get the initial error. The result is however "failure"

**Comment by ikwattro** [comment]
@AndreasHenningsson 

Did you look at my comment above ? What does your training file look now ?

**Comment by AndreasHenningsson** [comment]
Yes I Think so.
I acctually created a file based on the above example (attcahed)

[train.zip](https://github.com/graphaware/neo4j-nlp-opennlp/files/1808230/train.zip)

**Comment by ikwattro** [comment]
And what exact query did you run? The exact same file is working fine on our side.

**Comment by AndreasHenningsson** [comment]
@ikwattro 
CALL ga.nlp.processor.train({textProcessor: "com.graphaware.nlp.processor.opennlp.OpenNLPTextProcessor", modelIdentifier: "test", alg: "ner", inputFile: "C:/Users/66055036/Desktop/train.test", trainingParameters: {iter: 10}})

**Comment by AndreasHenningsson** [comment]
@ikwattro 
I solved it by removing c:

:-)
